### ISSUE TITLE
Question about stylua.toml

### ISSUE THREAD

**Issue by ashrasmun** [wesleimp/stylua.nvim#1]
Hello,

I would like to ask, how can one pass their own `stylua.toml` to this plugin? I tried '[ckipp01/stylua-nvim](https://github.com/ckipp01/stylua-nvim)' but I couldn't make it work, although I saw the ability to point to specific .toml file in there.

Kind Regards

**Comment by wesleimp** [comment]
@ashrasmun It's not possible yet. This plugin try to find the `stylua.toml` or `.stylua.toml` recursively from the current execution path to root (the folder that contains `.git` or `$HOME`).

It would be awesome to have this feature. PRs are welcome, otherwise I'm gonna do this ASAP.

Thanks for asking
